### PR TITLE
 FEATURE: Create DriverAvailabilityCreatePage (Driver Availiability) #18

### LINKED ISSUE #18: FEATURE: Create DriverAvailabilityCreatePage (Driver Availiability)
Acceptance Criteria:

- [ ] Create a working page for indexing called `DriverAvailabilityCreatePage.js`
- [ ] Create a test file `DriverAvailabilityCreatePage.test.js` to test the created page.
- [ ] There should be a corresponding storybook called `DriverAvailabilityCreatePage.stories.js`

### PR DESCRIPTION
**Pull request by dhwang154**
I created the DriverAvailabilityCreatePage.js, DriverAvailabilityCreatePage.test.js, and DriverAvailabilityCreatePage.stories.js.
Below includes screenshots of the tests.
storybook:
storybook
npm test:
npm test
npm run coverage:
npm run coverage
npm stryker run: 
npm stryker run
This closes #18

### CODE REVIEW

**Review by wesley-hung — COMMENTED** [review]
Loosk good to me Vidit!

**Review by wesley-hung — APPROVED** [review]
good work daniel!

**Comment by dhwang154** [comment]
added regex test (09:00AM)

**Review by notaryaman — DISMISSED** [review]

**Comment by notaryaman** [comment]
LGTM!!

**Review by andrewpengucsb — APPROVED** [review]
LGTM

**Review by viditagrawal — APPROVED** [review]
good work!

**Pull request merged**
