### PR TITLE
DELETE for Driver Availability Controller (Driver Availability)

### LINKED ISSUE #13: FEATURE: DELETE for Driver Availability Controller (Driver Availability)
Acceptance Criteria: 

`DELETE /api/driverAvailability` that deletes an availability if owned by current user.

### PR DESCRIPTION
**Pull request by notaryaman**
adds DELETE endpoint for Driver Availability Controller, enter ID for in ID space to delete availability

working deployment: https://project-notaryaman-dev.dokku-16.cs.ucsb.edu/

image

closes #13

### CODE REVIEW

**Review by AllenHsm — APPROVED** [review]
LGTM!

**Review by Aasish-Virjala — CHANGES_REQUESTED** [review]
Have a better description. Also, have push these changes to a dev deployment on dokku so we can see the changes on swagger.

**Review by wesley-hung — APPROVED** [review]
LGTM

**Review by Aasish-Virjala — APPROVED** [review]
LGTM

**Pull request merged**
