### PR TITLE
FEATURE: Create DriverAvailabilityIndexPage (Driver Availability)

### PR DESCRIPTION
**Pull request by viditagrawal**
image
image
 Create a working page for indexing called DriverAvailabilityIndexPage.js
 Create a test file DriverAvailabilityIndexPage.test.js to test the created page.
 There should be a corresponding storybook called DriverAvailabilityIndexPage.stories.js

### CODE REVIEW

**Review by wesley-hung — DISMISSED** [review]
Great work! LGTM Vidit

**Review by AllenHsm — DISMISSED** [review]
LGTM! Good job vidit!

**Review by dhwang154 — DISMISSED** [review]
good changes!

**Review by wesley-hung — COMMENTED** [review]
Looks good Vidit!

**Review by wesley-hung — DISMISSED** [review]
LGTM!

**Review by AllenHsm — DISMISSED** [review]
LGTM! Great work

**Review by wesley-hung — APPROVED** [review]
the create page is looking spiffy! good work vidit!

**Review by andrewpengucsb — APPROVED** [review]
LGTM

**Pull request merged**
