### PR TITLE
Wt driver availability admin get all endpoint and get by id endpoint

### LINKED ISSUE #14: FEATURE: Get for Admins in Driver Availability Controller (Driver Availability)
Acceptance Criteria:

- [x] `GET /api/driverAvailability/admin/all` that gets all driver availabilities.

- [x] `GET /api/driverAvailability/admin?id=123` that gets a specific driver availability.

### PR DESCRIPTION
**Pull request by wesleytruong**
DriverAvailability admin endpoints

/api/driverAvailability/admin/all endpoint:
- gets all driver availability requests in the repository and returns them only if the request comes from a user with admin access

/api/driverAvailability/admin?id=x endpoint:
- returns the driver availability row that corresponds to the id

https://gauchoride-wesleytruong-dev.dokku-16.cs.ucsb.edu/swagger-ui/index.html#/
closes #14

### CODE REVIEW

**Review by Aasish-Virjala — CHANGES_REQUESTED** [review]
Description......deployment......I have no idea what this PR does, no proof that any of it works, etc

**Review by Aasish-Virjala — DISMISSED** [review]
Cool, I like the updated description.

**Review by dhwang154 — APPROVED** [review]
Looks good to me!

**Review by Aasish-Virjala — APPROVED** [review]
LGTM

**Pull request merged**
