### PR TITLE
 FEATURE: Create DriverAvailabilityForm (Driver Availability) #16

### LINKED ISSUE #16: FEATURE: Create DriverAvailabilityForm (Driver Availability)
Acceptance Criteria: 

- [ ] There is a react component `DriverAvailabilityForm.js` that is suitable for use on the pages described in the acceptance criteria

- [ ] There is a react component `DriverAvailabilityForm.test.js` that covers all tests for `DriverAvailabilityForm.js`

- [ ] There are storybook entries

### PR DESCRIPTION
**Pull request by dhwang154**
I added the DriverAvailabilityForm.js, DriverAvailabilityForm.test.js, and storybook entries. Below includes screenshots of the tests.

Storybook: 
Screenshot 2024-03-05 at 9 42 46 PM
Screenshot 2024-03-05 at 9 42 54 PM
npm test: 
npm test
npm run coverage:
npm run coverage
npx stryker run -m src/main/components/DriverAvailability/DriverAvailabilityForm.test.js:
mutation
This closes #16.

### CODE REVIEW

**Review by AllenHsm — APPROVED** [review]
LGTM!

**Review by viditagrawal — APPROVED** [review]
looks great1

**Review by andrewpengucsb — CHANGES_REQUESTED** [review]
Missing input regex for day and times

**Comment by dhwang154** [comment]
> Missing input regex for day and times

added regex for days and time (AM, PM) in form and test.

**Review by AllenHsm — APPROVED** [review]
LGTM!!

**Review by andrewpengucsb — CHANGES_REQUESTED** [review]
image
Message is confusing, should be different when the input is wrong, rather than just say that input is required

**Comment by dhwang154** [comment]
> image Message is confusing, should be different when the input is wrong, rather than just say that input is required

added new error message for both day, and start time and end time when the input is invalid. 
Screenshot 2024-03-08 at 12 21 12 PM

**Review by notaryaman — APPROVED** [review]

**Comment by notaryaman** [comment]
LGTM

**Review by andrewpengucsb — APPROVED** [review]
LGTM

**Pull request merged**
