### PR TITLE
Wt driver availability record and fixtures

### LINKED ISSUE #9: FEATURE: Database record and fixtures (Driver Availability)
Part of the Driver Availability Epic.

- [x] - [ ] There is an @Entity called DriverAvailability with fields: Long id, (type depends) driverId, String day, String startTime, String endTime, String notes.

- [x] There is a @Repository called DriverAvailabilityRepository.

- [x] There is a fixtures file driverAvailabilityFixtures.js.

After finishing this issue, look to work on issue #10

### PR DESCRIPTION
**Pull request by wesleytruong**
closes #9

### CODE REVIEW

**Review by dhwang154 — APPROVED** [review]
looks good!

**Review by Aasish-Virjala — DISMISSED** [review]
LGTM!

**Review by wesley-hung — CHANGES_REQUESTED** [review]
Change instances of "Long" to the primitive long, otherwise looks good Wesley!

**Review by wesley-hung — APPROVED** [review]
all good LGTM - other wesley

**Review by AllenHsm — APPROVED** [review]
LGTM! Great start Wesley!

**Pull request merged**
